In [1]:
import numpy as np
import pandas as pd

from folktables import adult_filter, public_coverage_filter, ACSIncome, ACSPublicCoverage, ACSMobility, ACSEmployment, BasicProblem
from aif360.datasets.adult_dataset import AdultDataset
from aif360.datasets.binary_label_dataset import BinaryLabelDataset

from feldman import gen_feldman_probs
from datasets import gen_new_adult

/Users/jessicadai/miniconda3/envs/distfair/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
pip install 'aif360[AdversarialDebiasing]'
pip install 'aif360[AdversarialDebiasing]'


In [2]:
ad = gen_new_adult(0, False, interv=True)

In [14]:
acs_data = pd.read_csv('../data_raw/acs_data.csv')
df = ACSIncome.df_to_numpy(acs_data)

In [15]:
df

(array([[30.,  6., 14., ..., 40.,  1.,  8.],
        [21.,  4., 16., ..., 20.,  1.,  1.],
        [65.,  2., 22., ...,  8.,  1.,  1.],
        ...,
        [61.,  1., 19., ..., 45.,  1.,  1.],
        [69.,  7., 24., ..., 45.,  1.,  6.],
        [40.,  1., 17., ..., 40.,  1.,  8.]]),
 array([False, False, False, ...,  True, False, False]),
 array([8, 1, 1, ..., 1, 6, 8]))

In [3]:
gen_feldman_probs(dataset='adult_new')

0.6175
0.6175
0.6175
0.6175
0.6175
0.6175
0.6175
0.6175
0.6175
0.6175


(      scores_pr  scores_tpr  scores_eo  scores_acc  label  group
 0      0.208278    0.206683   0.206957    0.208161    0.0    0.0
 1      0.222565    0.222361   0.222410    0.222433    1.0    1.0
 2      0.219234    0.220911   0.220717    0.219000    0.0    1.0
 3      0.245185    0.248927   0.248356    0.245722    0.0    1.0
 4      0.372425    0.380582   0.378658    0.373497    0.0    1.0
 ...         ...         ...        ...         ...    ...    ...
 9995   0.209046    0.208088   0.208399    0.208964    0.0    1.0
 9996   0.218909    0.216792   0.217030    0.218653    0.0    0.0
 9997   0.618651    0.624842   0.622823    0.619169    1.0    0.0
 9998   0.721042    0.722162   0.721495    0.721146    0.0    1.0
 9999   0.218985    0.219191   0.219593    0.219258    0.0    1.0
 
 [10000 rows x 6 columns],
 {'pr': 1.0, 'tpr': 0.1, 'eo': 0.2, 'acc': 0.9},
    repairlevel   avg_prd  avg_tprd   avg_eod   avg_acc    05_prd   05_tprd  \
 0          0.1  0.016780  0.014869  0.023921  0.62